### ISSUE TITLE
Bug - DQuery.setRowLimit() no longer works for Informix

### ISSUE THREAD

**Issue by toaomalkster** [gregorydgraham/DBvolution#1]
Consequently, queries that rely on being limited by number of rows returned are instead querying entire tables.

The problem is that InformixDBDefinition.supportsPagingNatively() returns false, so InformixDBDefinition.getLimitRowsSubClauseDuringSelectClause() doesn't add 'FIRST xxx' to the SQL string.

To replicate, assuming you have a database with a Vehicle table with PK 'uid_6', put a breakpoint in DBQuery.getAllRowsInternal() and execute the following, then watch to see whether it stops retrieving records after the first 5.
 
```java
Vehicle vehExample = new Vehicle();
vehExample.getUid_6().permittedRange(0, 100000);
DBQuery q = dbatabase.getDBQuery(vehExample);
q.setRowLimit(5);
List<DBQueryRow> records = q.getAllRows();
```

**Comment by gregorydgraham** [comment]
Just double-checked my info on FIRST and I'll need to use FIRST and SKIP to get paging working.

If FIRST and SKIP don't work well together then the existing code is correct.

Hopefully they do though :)

**Comment by gregorydgraham** [comment]
SKIP is not supported in your version of Informix, so I'm investigating an alternative for you.

**Comment by gregorydgraham** [comment]
Should be fixed now, the query is now limited with setRowLimit and paging works.
